name: Deploy GitHub Pages from LR1

on:
  push:
    branches:
      - main  # Запускаем деплой при каждом пуше в main
  workflow_dispatch:  # Позволяет вручную запускать Action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Настроить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Создать артефакт с сайтом
        run: |
          mkdir public
          cp -r LR1/* public/
          touch public/.nojekyll  # Отключаем Jekyll, если есть файлы с _

      - name: Развернуть в GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Ветка для GitHub Pages
          folder: public    # Папка, которую деплоим
          clean: true       # Удаляет старые файлы перед загрузкой

